server:
  port: 8848
spring:
  application:
#    应用名称可选
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie
      username: root
      password: root
#      url: jdbc:mysql://47.94.101.19:3306/reggie
#      username: reggie
#      password: reggie
  redis:
    host: 47.94.101.19
#    host: localhost
    port: 6379
    password: tian
    database: 0
  cache:
    redis:
      time-to-live: 1800000 #设置缓存数据的过期时间
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: E:\images\
#  path: /reggie/images/